name: Run tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  php-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.4, 8.3, 8.2, 8.1, 8.0, 7.4]

    name: P${{ matrix.php }}

    steps:
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: xdebug
          tools: php-cs-fixer, phpunit

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Git user
        run: |
          git config --global user.email "acr@antoniocarlosribeiro.com"; git config --global user.name "Antonio Ribeiro"

      - name: Install dependencies
        run: |
          php --version
          composer require --prefer-dist --no-interaction --no-suggest

      - name: Execute tests
        run: vendor/bin/phpunit

      - name: Execute PHPStan
        run: vendor/bin/phpstan analyse -c phpstan.neon
